from app.schemas.model_metadata import ModelMetadataArtifact
from app.utils.model_metadata_store import save_model_metadata_artifact


ARTIFACTS = [
    ModelMetadataArtifact(
        model_name="gbr_player_v2_1",
        task_type="player_points",
        feature_version="v2_1",
        training_window_start_gw=1,
        training_window_end_gw=22,
        evaluation_start_gw=23,
        evaluation_end_gw=27,
        metrics_summary={"val_mae": 0.947815},
        status="active",
        is_active=True,
        is_production_default=True,
        selected_reason="Best player-side model in Day56 experiments. Strongest MAE and good use of nonlinear feature interactions.",
        notes="Primary player production model.",
    ),
    ModelMetadataArtifact(
        model_name="elasticnet_player_v2_1",
        task_type="player_points",
        feature_version="v2_1",
        training_window_start_gw=1,
        training_window_end_gw=22,
        evaluation_start_gw=23,
        evaluation_end_gw=27,
        metrics_summary={"val_mae": 0.9917},
        status="active",
        is_active=True,
        is_production_default=False,
        selected_reason="Best linear player model. Kept as explainable backup.",
        notes="Secondary / backup player production model.",
    ),
    ModelMetadataArtifact(
        model_name="ridge_player_v2_1",
        task_type="player_points",
        feature_version="v2_1",
        training_window_start_gw=1,
        training_window_end_gw=22,
        evaluation_start_gw=23,
        evaluation_end_gw=27,
        metrics_summary={"val_mae": 1.003169},
        status="archived",
        is_active=False,
        is_production_default=False,
        selected_reason="Archived because Elastic Net provided a stronger linear alternative.",
        notes="Archived Day56 ridge candidate.",
    ),
    ModelMetadataArtifact(
        model_name="lgbm_player_v2_1",
        task_type="player_points",
        feature_version="v2_1",
        training_window_start_gw=1,
        training_window_end_gw=22,
        evaluation_start_gw=23,
        evaluation_end_gw=27,
        metrics_summary={"val_mae": 0.9517},
        status="experimental",
        is_active=False,
        is_production_default=False,
        selected_reason="Strong but slightly weaker than the best GBR run. Keep experimental.",
        notes="Experimental tree-based player model.",
    ),
    ModelMetadataArtifact(
        model_name="baseline_rollavg_v0",
        task_type="player_points",
        feature_version="v0",
        training_window_start_gw=1,
        training_window_end_gw=27,
        evaluation_start_gw=28,
        evaluation_end_gw=30,
        metrics_summary={"overall_mae": 1.0351},
        status="archived",
        is_active=False,
        is_production_default=False,
        selected_reason="Older rolling-average baseline retained as historical reference only.",
        notes="Archived baseline reference.",
    ),
    ModelMetadataArtifact(
        model_name="baseline_rollavg_v1",
        task_type="player_points",
        feature_version="v1",
        training_window_start_gw=1,
        training_window_end_gw=30,
        evaluation_start_gw=28,
        evaluation_end_gw=30,
        metrics_summary={"overall_mae": 1.0},
        status="archived",
        is_active=False,
        is_production_default=False,
        selected_reason="Superseded by v2_1 model stack.",
        notes="Archived rolling-average reference.",
    ),
    ModelMetadataArtifact(
        model_name="ridge_rollform_v1",
        task_type="player_points",
        feature_version="v0",
        training_window_start_gw=1,
        training_window_end_gw=22,
        evaluation_start_gw=23,
        evaluation_end_gw=30,
        metrics_summary={"validation_mae": 0.9884},
        status="archived",
        is_active=False,
        is_production_default=False,
        selected_reason="Older ridge path superseded by newer v2_1 experiments.",
        notes="Archived historical ridge model.",
    ),
    ModelMetadataArtifact(
        model_name="match_gbc_v2",
        task_type="match_result",
        feature_version="v2",
        training_window_start_gw=1,
        training_window_end_gw=22,
        evaluation_start_gw=23,
        evaluation_end_gw=27,
        metrics_summary={"val_accuracy": 0.352941, "val_logloss": 1.220291},
        status="active",
        is_active=True,
        is_production_default=True,
        selected_reason="Best match-result classifier in Day57 experiments.",
        notes="Primary match production model.",
    ),
    ModelMetadataArtifact(
        model_name="match_goals_gbr_v2",
        task_type="match_goals",
        feature_version="v2",
        training_window_start_gw=1,
        training_window_end_gw=22,
        evaluation_start_gw=23,
        evaluation_end_gw=27,
        metrics_summary={
            "home_goals_mae": 0.9436,
            "away_goals_mae": 0.8653,
            "avg_goal_mae": 0.9045,
            "avg_goal_rmse": 1.1260,
        },
        status="experimental",
        is_active=False,
        is_production_default=False,
        selected_reason="Useful goals prototype, but not the main production match-result model.",
        notes="Experimental goals / scoreline foundation.",
    ),
    ModelMetadataArtifact(
        model_name="match_logreg_v2",
        task_type="match_result",
        feature_version="v2",
        training_window_start_gw=1,
        training_window_end_gw=22,
        evaluation_start_gw=23,
        evaluation_end_gw=27,
        metrics_summary={"val_accuracy": 0.1961, "val_logloss": 1.5232},
        status="archived",
        is_active=False,
        is_production_default=False,
        selected_reason="Archived because tree-based match model clearly outperformed it.",
        notes="Archived match logistic regression candidate.",
    ),
    ModelMetadataArtifact(
        model_name="match_lgbm_v2",
        task_type="match_result",
        feature_version="v2",
        training_window_start_gw=1,
        training_window_end_gw=22,
        evaluation_start_gw=23,
        evaluation_end_gw=27,
        metrics_summary={"val_accuracy": 0.2941, "val_logloss": 1.6361},
        status="archived",
        is_active=False,
        is_production_default=False,
        selected_reason="Interesting but weaker than the best GBC configuration.",
        notes="Archived experimental LightGBM match model.",
    ),
    ModelMetadataArtifact(
        model_name="match_baseline_v0",
        task_type="match_result",
        feature_version="match_v0",
        training_window_start_gw=1,
        training_window_end_gw=29,
        evaluation_start_gw=30,
        evaluation_end_gw=30,
        metrics_summary={"accuracy": 0.4, "logloss": 1.1762},
        status="archived",
        is_active=False,
        is_production_default=False,
        selected_reason="Historical baseline kept only for reference.",
        notes="Archived match baseline reference.",
    ),
    ModelMetadataArtifact(
        model_name="match_logreg_v0",
        task_type="match_result",
        feature_version="match_v0",
        training_window_start_gw=1,
        training_window_end_gw=29,
        evaluation_start_gw=30,
        evaluation_end_gw=30,
        metrics_summary={"accuracy": 0.2, "logloss": 1.5399},
        status="archived",
        is_active=False,
        is_production_default=False,
        selected_reason="Older match logreg path superseded by v2 experiments.",
        notes="Archived old match logistic regression reference.",
    ),
]


def main() -> None:
    for artifact in ARTIFACTS:
        save_model_metadata_artifact(artifact)


if __name__ == "__main__":
    main()
