"""create player gw stats

Revision ID: 3517672a85b1
Revises: e435167e061b
Create Date: 2026-01-23 09:45:00.518134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3517672a85b1'
down_revision: Union[str, Sequence[str], None] = 'e435167e061b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_gw_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('gw', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('goals_scored', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('clean_sheets', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'gw', name='uq_player_gw_stats_player_id_gw')
    )
    op.create_index(op.f('ix_player_gw_stats_gw'), 'player_gw_stats', ['gw'], unique=False)
    op.create_index(op.f('ix_player_gw_stats_player_id'), 'player_gw_stats', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_gw_stats_player_id'), table_name='player_gw_stats')
    op.drop_index(op.f('ix_player_gw_stats_gw'), table_name='player_gw_stats')
    op.drop_table('player_gw_stats')
    # ### end Alembic commands ###
