"""create gameweeks

Revision ID: e435167e061b
Revises: e0e7a44084d4
Create Date: 2026-01-21 09:40:55.130076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e435167e061b'
down_revision: Union[str, Sequence[str], None] = 'e0e7a44084d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameweeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gw', sa.Integer(), nullable=False),
    sa.Column('deadline_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_next', sa.Boolean(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gameweeks_gw'), 'gameweeks', ['gw'], unique=True)
    op.create_index(op.f('ix_gameweeks_is_current'), 'gameweeks', ['is_current'], unique=False)
    op.create_index(op.f('ix_gameweeks_is_finished'), 'gameweeks', ['is_finished'], unique=False)
    op.create_index(op.f('ix_gameweeks_is_next'), 'gameweeks', ['is_next'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gameweeks_is_next'), table_name='gameweeks')
    op.drop_index(op.f('ix_gameweeks_is_finished'), table_name='gameweeks')
    op.drop_index(op.f('ix_gameweeks_is_current'), table_name='gameweeks')
    op.drop_index(op.f('ix_gameweeks_gw'), table_name='gameweeks')
    op.drop_table('gameweeks')
    # ### end Alembic commands ###
